version: '2'
services:
  db_mongo:
    extends:
      file: base.yml
      service: mongo
    container_name: db_mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo/desarrollo:/home/developt
    networks:
      app_net:
        ipv4_address: '$MONGO_IP'



  web_flask:
    extends:
      file: base.yml
      service: flask
    container_name: web_flask
    build:
      args:
        - FLASK_ENV=dev
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - ./flask/projects:/home/desarrollo
    networks:
      app_net:
        ipv4_address: '$FLASK_IP'
    command: python apps/run.py




networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 140.24.0.0/24
